import { Jost, Roboto, Poppins, Inter } from 'next/font/google';
import { FormContextProvider } from '@/components/web-app/shared/FormContextProvider';

import "@/styles/globals.css";



const jost = Jost({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-jost',
});

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-roboto',
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${jost.variable} ${poppins.variable} ${inter.variable} ${roboto.variable} antialiased`}
      >
        <FormContextProvider>
            {children}
        </FormContextProvider>
      </body>
    </html>
  );
}


export const metadata = {
  title: "AutoInvoice - Invoice Generator",

  description: "Generated by create next app",
};

